// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLycheePath():Promise<string>;

export function IsLycheeRunning():Promise<boolean>;

export function StartLychee(arg1:string):Promise<void>;

export function StopLychee():Promise<void>;
