// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLycheePath() {
  return window['go']['main']['App']['GetLycheePath']();
}

export function IsLycheeRunning() {
  return window['go']['main']['App']['IsLycheeRunning']();
}

export function StartLychee(arg1) {
  return window['go']['main']['App']['StartLychee'](arg1);
}

export function StopLychee() {
  return window['go']['main']['App']['StopLychee']();
}
