// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoStartLychee() {
  return window['go']['main']['App']['AutoStartLychee']();
}

export function ExportPipeline(arg1) {
  return window['go']['main']['App']['ExportPipeline'](arg1);
}

export function GetLycheePath() {
  return window['go']['main']['App']['GetLycheePath']();
}

export function GetLycheeStatus() {
  return window['go']['main']['App']['GetLycheeStatus']();
}

export function GetOAuthConfig(arg1) {
  return window['go']['main']['App']['GetOAuthConfig'](arg1);
}

export function HandleOAuthCallback(arg1, arg2) {
  return window['go']['main']['App']['HandleOAuthCallback'](arg1, arg2);
}

export function ImportPipeline() {
  return window['go']['main']['App']['ImportPipeline']();
}

export function IsLycheeRunning() {
  return window['go']['main']['App']['IsLycheeRunning']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function StartLychee(arg1) {
  return window['go']['main']['App']['StartLychee'](arg1);
}

export function StopLychee() {
  return window['go']['main']['App']['StopLychee']();
}
