// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoStartLychee():Promise<string>;

export function ExportPipeline(arg1:string):Promise<string>;

export function GetLycheePath():Promise<string>;

export function GetLycheeStatus():Promise<Record<string, any>>;

export function GetOAuthConfig(arg1:string):Promise<Record<string, string>>;

export function HandleOAuthCallback(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ImportPipeline():Promise<string>;

export function IsLycheeRunning():Promise<boolean>;

export function Login(arg1:string):Promise<string>;

export function StartLychee(arg1:string):Promise<void>;

export function StopLychee():Promise<void>;
